/**
 * 工单评价
 */
CREATE TABLE TB_WORK_ORDER_EXT
  (
    WORK_ORDER_ID VARCHAR2(100 BYTE),
    ADDRESS      VARCHAR2(255 BYTE),
    TIME DATE
  )
/**
 * 手机版本信息
 */
CREATE TABLE TB_APP_VERSION
  (
    APP_VERSION     VARCHAR2(50 BYTE),
    MODEL           VARCHAR2(50 BYTE),
    ANDROID_VERSION VARCHAR2(50 BYTE),
    MASTER_ID       VARCHAR2(50 BYTE),
    PHONE           VARCHAR2(50 BYTE)
  )
/**
 * 更新app
 */
CREATE TABLE TB_UPDATE_APP_VERSION(
id number(10),
app_version varchar2(50),
url varchar2(100),
notice varchar2(100),
flag number(10)
);
/**
 *灰度发布用户
 */
CREATE TABLE GRAY_RELEASE_USER(
phone varchar2(50)
);
/**
 * 撤单
 */
CREATE TABLE TB_WORK_ORDER_BACKUP
  (
    FID      VARCHAR2(100 BYTE),
    ORDER_ID VARCHAR2(100 BYTE),
    WORK_NO  VARCHAR2(100 BYTE),
    SEND_DATE DATE,
    SENDER         VARCHAR2(100 BYTE),
    PLAT_FORM_ID   VARCHAR2(100 BYTE),
    PLAT_FORM_NAME VARCHAR2(100 BYTE),
    FRANCHISEE_ID  VARCHAR2(100 BYTE),
    MASTER_ID      VARCHAR2(100 BYTE),
    STATUS         NUMBER,
    GIVE_REASONS   VARCHAR2(255 BYTE),
    AMOUNT         NUMBER,
    SINGER        VARCHAR2(100 BYTE),
    SING_TIME DATE,
    SERVICE_MAN        VARCHAR2(100 BYTE),
    SERVICE_FEEDBACK   VARCHAR2(255 BYTE),
    CUS_NAME           VARCHAR2(100 BYTE),
    CUS_ADDRESS        VARCHAR2(255 BYTE),
    CUS_TEL            VARCHAR2(100 BYTE),
    SENDER_ID          VARCHAR2(100 BYTE),
    SERVICE_MAN_ID     VARCHAR2(100 BYTE),
    ORDER_SN           NUMBER,
    MASTER_NAME        VARCHAR2(100 BYTE),
    STATUS_DISPLAY     VARCHAR2(100 BYTE),
    FEEDBACK_CONTENT   VARCHAR2(255 BYTE),
    INSTALL_LINK_PHONE VARCHAR2(100 BYTE),
    INSTALL_LINK_MAN   VARCHAR2(100 BYTE),
    FEEDBACK_TIME DATE,
    FEEDBACK_MAN         VARCHAR2(100 BYTE),
    INSTALL_LINK_ADDRESS VARCHAR2(255 BYTE),
    EVAL_SCORE           NUMBER,
    CUSTOMER_EVAL        VARCHAR2(255 BYTE),
    IS_CUS_CONFIRM       NUMBER,
    REPORT_MAN           VARCHAR2(100 BYTE),
    COMPLETE_DATE DATE,
    TYPE VARCHAR2(100 BYTE),
    BILL_DATE DATE,
    MASTER_PHONE         VARCHAR2(100 BYTE),
    WORK_ORDER_MASTER_ID VARCHAR2(100 BYTE),
    BOOKING_TIME DATE,
    DISPATCH_SN           VARCHAR2(200 BYTE),
    DISPATCH_MEMO        VARCHAR2(200 BYTE),
    MEMO2                 VARCHAR2(2000 BYTE),
    STORE_NAME            VARCHAR2(200 BYTE),
    WAREHOUSE_NAME        VARCHAR2(200 BYTE),
    FEEDBACK_VALIDITY     VARCHAR2(100 BYTE),
    IS_FEE                VARCHAR2(10 BYTE),
    CUSTOMER_EVAL_SCORE   NUMBER,
    FEEDBACK_REMARK       VARCHAR2(2000 BYTE),
    SATISFACTION1         NUMBER,
    SATISFACTION2         NUMBER,
    SATISFACTION3         NUMBER,
    CHECK_CODE            VARCHAR2(100 BYTE),
    OUT_ORDER_SN          VARCHAR2(100 BYTE),
    FEEDBACK_STATUS       VARCHAR2(100 BYTE),
    AUDIT_STATUS          NUMBER,
    REMARK                VARCHAR2(2000 BYTE),
    IS_TMALL_ORDER        NUMBER,
    OMS_DISPATCH_NO       VARCHAR2(200 BYTE),
    EVAL_SERVICE_COMPLETE NUMBER DEFAULT 0,
    EVAL_DELIVERY        NUMBER DEFAULT 0,
    EVAL_INSTALL          NUMBER DEFAULT 0,
    EVAL_PHONE_BACK       NUMBER DEFAULT 0,
    VIEW_TIME DATE DEFAULT NULL,
    DETAIL       VARCHAR2(255 BYTE),
    REVOKE_CAUSE VARCHAR2(2000 BYTE),
    REVOKE_TIME DATE,
    REVOKE_NAME VARCHAR2(100 BYTE)
  )
  /**
   * 工人表
   */
  create table tb_worker(
    "FID"                      VARCHAR2(100 BYTE),
    "NAME"                     VARCHAR2(100 BYTE),
    "PHONE"                    VARCHAR2(100 BYTE),
    "SEX"                      VARCHAR2(100 BYTE),
    "PLAT_FORM_ID"             NUMBER,
    "LEADER_ID"                VARCHAR2(100 BYTE),
    "PLAT_FORM_NAME"           VARCHAR2(100 BYTE),
    "IDENTITY_CARD"            VARCHAR2(100 BYTE),
    "CITY"                     VARCHAR2(100 BYTE),
    "WORK_TYPE"                VARCHAR2(2000 BYTE),
    "WORK_TYPE_DISPLAY"        VARCHAR2(255 BYTE),
    "SERVICE_PROVINCE"         VARCHAR2(100 BYTE),
    "SERVICE_CITY"             VARCHAR2(100 BYTE),
    "SERVICE_DISTRICT"         VARCHAR2(100 BYTE),
    "BANK_ACCOUNT"             VARCHAR2(100 BYTE),
    "BANK_NAME"                VARCHAR2(100 BYTE),
    "BANK_NUMBER"              VARCHAR2(100 BYTE),
    "SOS_LINK_MAN"             VARCHAR2(100 BYTE),
    "RELATIONSHIP"             VARCHAR2(100 BYTE),
    "LINK_PHONE"               VARCHAR2(100 BYTE),
    "SERVICE_PROVINCE_DISPLAY" VARCHAR2(100 BYTE),
    "SERVICE_CITY_DISPLAY"     VARCHAR2(100 BYTE),
    "SERVICE_DISTRICT_DISPLAY" VARCHAR2(2000 BYTE),
    "STATUS"                   NUMBER(1,0),
    "CREATE_TIME" DATE,
    "AGE"            VARCHAR2(100 BYTE),
    "CHAT"           VARCHAR2(100 BYTE),
    "HAVE_CAR"       VARCHAR2(10 BYTE),
    "HAVE_TOOLS"     VARCHAR2(10 BYTE),
    "HAVA_INSURANCE" VARCHAR2(10 BYTE),
    "REMARK"         VARCHAR2(255 BYTE),
    "CREATE_USER_ID" VARCHAR2(100 BYTE),
    "AUDIT_USER_ID"  VARCHAR2(100 BYTE),
    "AUDIT_TIME" DATE,
    "IMAGE_URL1"           VARCHAR2(255 BYTE),
    "AUDIT_USER"           VARCHAR2(100 BYTE),
    "IMAGE_URL2"           VARCHAR2(255 BYTE),
    "IMAGE_URL3"           VARCHAR2(255 BYTE),
    "MASTER_NO"            VARCHAR2(100 BYTE),
    "CAR_TYPE"             VARCHAR2(100 BYTE),
    "MASTER_FROM"          VARCHAR2(100 BYTE),
    "BRANCH"               VARCHAR2(100 BYTE),
    "CERTIFICATION_STATUS" NUMBER DEFAULT 0,
    "WORK_SKILL"           VARCHAR2(200 BYTE),
    "LOCKING"              VARCHAR2(10 BYTE),
    "TAG"                  VARCHAR2(10 BYTE)
  )
  /**
   * tb_app_user表添加 user_type
   */
  alter table tb_app_user add (user_type number(10));
  /**
   * 
   */
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  